version: "3.9"
services:
  fastnerf:
    image:
      f2-nerf-image
    container_name:
      f2-nerf-container
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /mnt/e/Datasets:/home/user/data:cached
      - ..:/home/user/workspace/:cached
    command: bash
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    tty: true
    # stdin_open: true
